phraseapp:
  project_id: 908d814b409fb67ab7103a3e43c982fc
  push:
    sources:
      - file: ./locale/<locale_code>/<locale_name>.po
        params:
          file_format: gettext
          tags: slush-demo
          skip_upload_tags: true
          update_translations: true
  pull:
    targets:
      - file: ./locale/<locale_code>/<locale_name>.po
        params:
          file_format: gettext
          include_empty_translations: true
          tag: slush-demo
